### PR TITLE
Gitops wee

### PR DESCRIPTION
**Pull request by Draiken**

### CODE REVIEW

**Comment by Draiken** [comment]
lala

**Comment by Draiken** [comment]
lele

**Comment by Draiken** [comment]
laaaa

**Comment by Draiken** [comment]
create release environment

**Comment by Draiken** [comment]
create release environment

**Comment by Draiken** [comment]
create release environment

**Comment by Draiken** [comment]
create release environment

**Comment by luiz-release-test** [comment]
create release environment

**Comment by Draiken** [comment]
create release environment

**Pull request closed without merging**
